# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '31f55ca7096cec08d0dc03913622a5d7'
  config.secret_key = '38abef890b863937ebdcbb82714b4db7'
  config.default_from = 'THPBordeaux@gmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end